# 第二十四章练习题参考答案

1. (a) 断言可以用来检测两种问题:第一种是如果程序正确就不应该发生的问题,第二种是超出程序控制范围的问题。请解释为什么`assert`更适用于第一种问题。

   (b) 请举出三个超出程序控制范围的问题的例子。

   #### 答案

   (a) 确保程序在假设的条件成立的情况下,运算结果是一致的.

   (b)  操作系统的强制终止信号、硬件故障、电力中断

   

2. 编写`assert`函数调用,当名为`top`的变量取值为`NULL`时使程序终止。

   #### 答案

   ```c
   assert(top != NULL);
   ```

   

3. 修改19.4节的`stackADT2.c`文件,用assert取代if语句来测试错误。(注意,不再需要`terminate`函数了,可以删除它。)

   #### 答案

   ```c
   #include <stdio.h>
   #include <stdlib.h>
   #include <assert.h>
   #include "stackADT2.h"
   
   struct stack_type {
     Item *contents;
     int top;
     int size;
   };
   
   Stack create(int size){
     Stack s = malloc(sizeof(struct stack_type));
     assert(s != NULL);
     s->contents = malloc(size * sizeof(Item));
     assert(s->contents != NULL); /* Warning: memleak for s!!! */
     s->top = 0;
     s->size = size;
     return s;
   }
   
   void destroy(Stack s){
     free(s->contents);
     free(s);
   }
   
   void make_empty(Stack s){
     s->top = 0;
   }
   
   bool is_empty(Stack s){
     return s->top == 0;
   }
   
   bool is_full(Stack s){
     return s->top == s->size;
   }
   
   void push(Stack s, Item i){
     assert(!is_full(s));
     s->contents[s->top++] = i;
   }
   
   Item pop(Stack s){
     assert(!is_empty(s));
     return s->contents[--s->top];
   }
   ```

   

4. (a) 编写一个名为`try_math_fcn`的“包装”函数来调用数学函数(假定有一个`double`类型的参数,并返回一个`double`类型的值),然后检查调用是否成功。下面是使用`try_math_fcn`函数的例子:

   ```c
   y = try_math_fcn(sqrt, x, "Error in call of sqrt");
   ```

   如果调用`sqrt(x)`成功, `try_math_fcn`返回sqrt函数的计算结果。如果调用失败, `try_math_fcn`需要调用`perror`显示消息`Error in call of sqrt`,然后调用`exit`函数终止程序。

   (b) 编写一个与`try_math_fcn`具有相同效果的宏,但是要求使用函数的名字来构造出错消息:

   ```c
   y = TRY_MATH_FCN(sqrt, x);
   ```

   如果调用`sqrt`失败,显示的出错消息应该是"Error in call of sqrt",提示:让`TRY_MATH_FCN`调用call `try_math_fcn` .

   #### 答案

   (a)

   ```c
   double try_math_fcn(double (*func)(double), double x, const char *message){
       errno = 0;
       double ret = (*func)(x);
       if (errno == 0)
           return ret;
       perror(message);
       exit(EXIT_FAILURE);
   }
   ```

   (b)

   ```c
   #define TRY_MATH_FCN(f,x) (try_math_fcn((f), (x), "Error in call of " #f))
   ```

5. I在`inventory.c`程序(见16.3节)中, main函数用一个`for`循环来提示用户输入一个操作码,然后读入码并调用`insert`, `search`, `update`或`print`.在`main`函数中加入一个`setjmp`调用,要求使随后的`longjmp`调用会返回到`for`循环。(在调用`longjmp`函数后,提示用户输入一个操作码,随后程序正常执行。) `setjmp`需要一个`jmp_buf`类型的变量,这个变量应该在哪儿声明呢?

   #### 答案

   见`exercise24.5.c`

   

   

